import { getServerSession } from "next-auth";
import NavBar from "./NavBar";
import { authOptions } from "./api/auth/[...nextauth]";
import { SessionProvider } from "next-auth/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <>
      <NavBar />
      <div>{children}</div>
    </>
  );
}
